# Generated by Django 4.2.7 on 2024-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ratings_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('kitchen', 'Kitchen'), ('fashion', 'Fashion'), ('grocery', 'Grocery')], default='unknown', max_length=50),
        ),
    ]
