# Generated by Django 4.2.7 on 2024-08-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cart_alter_product_category_cartitem_cart_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('kitchen', 'Kitchen'), ('fashion', 'Fashion'), ('grocery', 'Grocery'), ('mobile', 'Mobile'), ('camera', 'Camera'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('books', 'Books'), ('furniture', 'Furniture'), ('beauty', 'Beauty'), ('best_selling_products', 'Best_selling_products'), ('new_arrivals', 'New_arrivals')], default='unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
