# Generated by Django 4.2.7 on 2024-08-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_itemstatus_itemstatu'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatu',
            name='status',
            field=models.CharField(choices=[('payment_conformation', 'Payment_conformation'), ('packed', 'Packed'), ('intransit', 'Intransit'), ('delivered', 'Delivered')], default='', max_length=100),
        ),
    ]
