# Generated by Django 5.1.5 on 2025-04-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
